server:
  port: ${SERVER_PORT:8080}
  tomcat:
    connection-timeout: 10s
    keep-alive-timeout: 5s
    max-keep-alive-requests: 100
management:
  endpoints:
    web:
      exposure:
        include: health,info
